import { useState, useEffect, useMemo } from 'react';

// Enhanced emoji search data with keywords
const EMOJI_KEYWORDS = {
  // Smileys & Emotion
  '😀': ['grinning', 'happy', 'smile', 'joy'],
  '😃': ['grinning', 'happy', 'smile', 'joy'],
  '😄': ['grinning', 'happy', 'smile', 'joy', 'laugh'],
  '😁': ['grinning', 'happy', 'smile', 'joy'],
  '😆': ['laughing', 'happy', 'smile', 'joy', 'laugh'],
  '😅': ['sweat', 'smile', 'relief', 'nervous'],
  '🤣': ['rolling', 'laugh', 'funny', 'hilarious'],
  '😂': ['tears', 'laugh', 'funny', 'crying'],
  '🙂': ['smile', 'happy', 'slight'],
  '🙃': ['upside', 'down', 'silly'],
  '😉': ['wink', 'flirt', 'playful'],
  '😊': ['blush', 'happy', 'smile', 'pleased'],
  '😇': ['angel', 'innocent', 'halo'],
  '🥰': ['love', 'hearts', 'adore', 'crush'],
  '😍': ['heart', 'eyes', 'love', 'crush'],
  '🤩': ['star', 'eyes', 'excited', 'wow'],
  '😘': ['kiss', 'love', 'heart'],
  '😗': ['kiss', 'whistle'],
  '☺️': ['smile', 'happy', 'relaxed'],
  '😚': ['kiss', 'closed', 'eyes'],
  '😙': ['kiss', 'smile'],
  '😋': ['yum', 'tongue', 'delicious', 'tasty'],
  '😛': ['tongue', 'playful', 'silly'],
  '😜': ['wink', 'tongue', 'playful', 'silly'],
  '🤪': ['crazy', 'wild', 'silly', 'zany'],
  '😝': ['tongue', 'closed', 'eyes', 'playful'],
  '🤑': ['money', 'rich', 'dollar', 'greedy'],
  '🤗': ['hug', 'embrace', 'hands'],
  '🤭': ['giggle', 'secret', 'oops'],
  '🤫': ['shush', 'quiet', 'secret'],
  '🤔': ['thinking', 'hmm', 'consider'],
  '😐': ['neutral', 'meh', 'expressionless'],
  '😑': ['expressionless', 'blank', 'meh'],
  '😶': ['no', 'mouth', 'quiet', 'silent'],
  '😏': ['smirk', 'smug', 'sly'],
  '😒': ['unamused', 'annoyed', 'meh'],
  '🙄': ['eye', 'roll', 'annoyed', 'whatever'],
  '😬': ['grimace', 'awkward', 'nervous'],
  '🤥': ['liar', 'pinocchio', 'lie'],
  '😔': ['sad', 'down', 'disappointed'],
  '😪': ['sleepy', 'tired', 'yawn'],
  '🤤': ['drool', 'sleep', 'want'],
  '😴': ['sleep', 'zzz', 'tired'],
  '😷': ['mask', 'sick', 'doctor', 'covid'],
  '🤒': ['sick', 'fever', 'ill'],
  '🤕': ['hurt', 'bandage', 'injured'],
  '🤢': ['sick', 'nausea', 'green'],
  '🤮': ['vomit', 'sick', 'puke'],
  '🤧': ['sneeze', 'sick', 'tissue'],
  '🥵': ['hot', 'sweat', 'heat'],
  '🥶': ['cold', 'freeze', 'blue'],
  '😵': ['dizzy', 'confused', 'dead'],
  '🤯': ['mind', 'blown', 'explode'],
  '🤠': ['cowboy', 'hat', 'western'],
  '🥳': ['party', 'celebrate', 'birthday'],
  '😎': ['cool', 'sunglasses', 'awesome'],
  '🤓': ['nerd', 'geek', 'smart'],
  '🧐': ['monocle', 'fancy', 'inspect'],
  '😕': ['confused', 'sad', 'disappointed'],
  '😟': ['worried', 'concerned', 'sad'],
  '🙁': ['sad', 'frown', 'disappointed'],
  '☹️': ['sad', 'frown', 'disappointed'],
  '😮': ['surprised', 'wow', 'oh'],
  '😯': ['surprised', 'hushed', 'wow'],
  '😲': ['shocked', 'surprised', 'wow'],
  '😳': ['flushed', 'embarrassed', 'shy'],
  '🥺': ['pleading', 'puppy', 'eyes', 'cute'],
  '😦': ['frowning', 'sad', 'disappointed'],
  '😧': ['anguished', 'worried', 'sad'],
  '😨': ['fearful', 'scared', 'afraid'],
  '😰': ['anxious', 'sweat', 'worried'],
  '😥': ['sad', 'sweat', 'disappointed'],
  '😢': ['cry', 'sad', 'tear'],
  '😭': ['sob', 'cry', 'tears', 'bawl'],
  '😱': ['scream', 'scared', 'shocked'],
  '😖': ['confounded', 'frustrated', 'sad'],
  '😣': ['persevere', 'struggle', 'frustrated'],
  '😞': ['disappointed', 'sad', 'dejected'],
  '😓': ['sweat', 'sad', 'tired'],
  '😩': ['weary', 'tired', 'frustrated'],
  '😫': ['tired', 'frustrated', 'fed', 'up'],
  '🥱': ['yawn', 'tired', 'sleepy', 'bored'],
  '😤': ['huff', 'angry', 'frustrated'],
  '😡': ['angry', 'mad', 'rage', 'red'],
  '😠': ['angry', 'mad', 'annoyed'],
  '🤬': ['swearing', 'angry', 'mad', 'symbols'],
  '😈': ['devil', 'evil', 'horns'],
  '👿': ['devil', 'angry', 'evil'],
  '💀': ['skull', 'death', 'dead'],
  '☠️': ['skull', 'crossbones', 'death', 'pirate'],
  '💩': ['poop', 'shit', 'crap'],
  '🤡': ['clown', 'funny', 'circus'],
  '👹': ['ogre', 'monster', 'red'],
  '👺': ['goblin', 'monster', 'red'],
  '👻': ['ghost', 'boo', 'spooky'],
  '👽': ['alien', 'ufo', 'space'],
  '👾': ['alien', 'monster', 'game'],
  '🤖': ['robot', 'ai', 'machine'],

  // People & Body
  '👋': ['wave', 'hello', 'hi', 'goodbye'],
  '🤚': ['raised', 'hand', 'stop'],
  '🖐️': ['hand', 'five', 'stop'],
  '✋': ['hand', 'stop', 'high', 'five'],
  '🖖': ['spock', 'vulcan', 'star', 'trek'],
  '👌': ['ok', 'okay', 'perfect', 'good'],
  '🤌': ['pinched', 'fingers', 'italian'],
  '🤏': ['pinch', 'small', 'tiny'],
  '✌️': ['peace', 'victory', 'two'],
  '🤞': ['crossed', 'fingers', 'luck', 'hope'],
  '🤟': ['love', 'you', 'sign'],
  '🤘': ['rock', 'on', 'metal', 'horns'],
  '🤙': ['call', 'me', 'hang', 'loose'],
  '👈': ['point', 'left', 'finger'],
  '👉': ['point', 'right', 'finger'],
  '👆': ['point', 'up', 'finger'],
  '🖕': ['middle', 'finger', 'rude'],
  '👇': ['point', 'down', 'finger'],
  '☝️': ['point', 'up', 'finger', 'one'],
  '👍': ['thumbs', 'up', 'good', 'yes', 'like', 'approve'],
  '👎': ['thumbs', 'down', 'bad', 'no', 'dislike'],
  '👊': ['fist', 'bump', 'punch'],
  '✊': ['fist', 'power', 'solidarity'],
  '🤛': ['fist', 'bump', 'left'],
  '🤜': ['fist', 'bump', 'right'],
  '👏': ['clap', 'applause', 'bravo', 'good', 'job'],
  '🙌': ['praise', 'hands', 'celebration', 'hooray'],
  '👐': ['open', 'hands', 'hug'],
  '🤲': ['palms', 'up', 'prayer', 'cupped'],
  '🤝': ['handshake', 'deal', 'agreement'],
  '🙏': ['pray', 'thanks', 'please', 'namaste'],
  '✍️': ['write', 'writing', 'author'],
  '💅': ['nail', 'polish', 'care', 'beauty'],
  '🤳': ['selfie', 'camera', 'phone'],
  '💪': ['muscle', 'strong', 'flex', 'bicep'],

  // Hearts & Love
  '❤️': ['heart', 'love', 'red'],
  '🧡': ['orange', 'heart', 'love'],
  '💛': ['yellow', 'heart', 'love'],
  '💚': ['green', 'heart', 'love'],
  '💙': ['blue', 'heart', 'love'],
  '💜': ['purple', 'heart', 'love'],
  '🖤': ['black', 'heart', 'love'],
  '🤍': ['white', 'heart', 'love'],
  '🤎': ['brown', 'heart', 'love'],
  '💔': ['broken', 'heart', 'sad', 'breakup'],
  '❣️': ['heart', 'exclamation', 'love'],
  '💕': ['two', 'hearts', 'love'],
  '💞': ['revolving', 'hearts', 'love'],
  '💓': ['beating', 'heart', 'love'],
  '💗': ['growing', 'heart', 'love'],
  '💖': ['sparkling', 'heart', 'love'],
  '💘': ['heart', 'arrow', 'cupid', 'love'],
  '💝': ['heart', 'box', 'gift', 'love'],
  '💟': ['heart', 'decoration', 'love'],

  // Nature
  '🔥': ['fire', 'hot', 'lit', 'flame', 'burn'],
  '💧': ['water', 'drop', 'tear', 'sweat'],
  '💦': ['sweat', 'droplets', 'water', 'splash'],
  '⭐': ['star', 'favorite', 'awesome'],
  '🌟': ['glowing', 'star', 'sparkle'],
  '✨': ['sparkles', 'magic', 'clean', 'shiny'],
  '⚡': ['lightning', 'bolt', 'electric', 'fast'],
  '☀️': ['sun', 'sunny', 'bright', 'day'],
  '🌙': ['moon', 'night', 'crescent'],
  '🌈': ['rainbow', 'pride', 'colorful'],
  '☔': ['rain', 'umbrella', 'weather'],
  '❄️': ['snow', 'cold', 'winter'],
  '🌊': ['wave', 'ocean', 'water', 'sea'],

  // Food & Drink
  '🍕': ['pizza', 'food', 'italian'],
  '🍔': ['burger', 'hamburger', 'food'],
  '🍟': ['fries', 'french', 'food'],
  '🌭': ['hot', 'dog', 'food'],
  '🥪': ['sandwich', 'food'],
  '🌮': ['taco', 'mexican', 'food'],
  '🌯': ['burrito', 'wrap', 'mexican'],
  '🍝': ['pasta', 'spaghetti', 'italian'],
  '🍜': ['ramen', 'noodles', 'soup'],
  '🍲': ['pot', 'food', 'stew'],
  '🥗': ['salad', 'healthy', 'green'],
  '🍿': ['popcorn', 'movie', 'snack'],
  '🧀': ['cheese', 'food'],
  '🥓': ['bacon', 'meat', 'breakfast'],
  '🥚': ['egg', 'breakfast', 'food'],
  '🍳': ['cooking', 'egg', 'pan'],
  '🥞': ['pancakes', 'breakfast', 'food'],
  '🧇': ['waffle', 'breakfast', 'food'],
  '🍞': ['bread', 'food', 'loaf'],
  '🥖': ['baguette', 'bread', 'french'],
  '🥨': ['pretzel', 'snack', 'food'],
  '🥐': ['croissant', 'bread', 'french'],
  '🍰': ['cake', 'dessert', 'birthday'],
  '🎂': ['birthday', 'cake', 'celebration'],
  '🧁': ['cupcake', 'dessert', 'sweet'],
  '🍪': ['cookie', 'dessert', 'sweet'],
  '🍩': ['donut', 'doughnut', 'sweet'],
  '🍭': ['lollipop', 'candy', 'sweet'],
  '🍬': ['candy', 'sweet', 'wrapper'],
  '🍫': ['chocolate', 'bar', 'sweet'],
  '🍯': ['honey', 'sweet', 'bee'],
  '☕': ['coffee', 'drink', 'caffeine', 'morning'],
  '🍵': ['tea', 'drink', 'hot'],
  '🥤': ['cup', 'straw', 'drink'],
  '🧃': ['juice', 'box', 'drink'],
  '🥛': ['milk', 'glass', 'drink'],
  '🍺': ['beer', 'drink', 'alcohol'],
  '🍻': ['beers', 'cheers', 'drink', 'celebration'],
  '🍷': ['wine', 'drink', 'alcohol'],
  '🥂': ['champagne', 'cheers', 'celebration'],
  '🍸': ['cocktail', 'drink', 'alcohol'],
  '🍹': ['tropical', 'drink', 'cocktail'],
  '🍾': ['champagne', 'bottle', 'celebration'],

  // Activities & Sports
  '⚽': ['soccer', 'football', 'ball', 'sport'],
  '🏀': ['basketball', 'ball', 'sport'],
  '🏈': ['football', 'american', 'ball', 'sport'],
  '⚾': ['baseball', 'ball', 'sport'],
  '🎾': ['tennis', 'ball', 'sport'],
  '🏐': ['volleyball', 'ball', 'sport'],
  '🏓': ['ping', 'pong', 'table', 'tennis'],
  '🎱': ['pool', 'billiards', 'eight', 'ball'],
  '🏆': ['trophy', 'winner', 'award', 'champion'],
  '🥇': ['gold', 'medal', 'first', 'winner'],
  '🥈': ['silver', 'medal', 'second'],
  '🥉': ['bronze', 'medal', 'third'],
  '🎯': ['target', 'bullseye', 'dart'],
  '🎮': ['video', 'game', 'controller'],
  '🕹️': ['joystick', 'game', 'arcade'],
  '🎲': ['dice', 'game', 'random'],
  '🎪': ['circus', 'tent', 'entertainment'],
  '🎭': ['theater', 'drama', 'masks'],
  '🎨': ['art', 'palette', 'creative'],
  '🎬': ['movie', 'film', 'cinema'],
  '🎤': ['microphone', 'sing', 'karaoke'],
  '🎧': ['headphones', 'music', 'listen'],
  '🎵': ['music', 'note', 'song'],
  '🎶': ['music', 'notes', 'song'],
  '🎸': ['guitar', 'music', 'rock'],
  '🎹': ['piano', 'keyboard', 'music'],
  '🥁': ['drum', 'music', 'beat'],
  '🎺': ['trumpet', 'music', 'brass'],
  '🎷': ['saxophone', 'music', 'jazz'],
  '🎻': ['violin', 'music', 'classical'],

  // Travel & Places
  '✈️': ['airplane', 'plane', 'travel', 'flight'],
  '🚗': ['car', 'automobile', 'vehicle'],
  '🚕': ['taxi', 'cab', 'car'],
  '🚙': ['suv', 'car', 'vehicle'],
  '🚌': ['bus', 'vehicle', 'public'],
  '🚎': ['trolley', 'bus', 'vehicle'],
  '🏎️': ['race', 'car', 'fast', 'formula'],
  '🚓': ['police', 'car', 'cop'],
  '🚑': ['ambulance', 'emergency', 'medical'],
  '🚒': ['fire', 'truck', 'emergency'],
  '🚐': ['van', 'vehicle'],
  '🚚': ['truck', 'delivery', 'vehicle'],
  '🚛': ['truck', 'semi', 'vehicle'],
  '🚜': ['tractor', 'farm', 'vehicle'],
  '🏍️': ['motorcycle', 'bike', 'vehicle'],
  '🛵': ['scooter', 'bike', 'vehicle'],
  '🚲': ['bicycle', 'bike', 'cycle'],
  '🛴': ['scooter', 'kick', 'vehicle'],
  '🛹': ['skateboard', 'skate', 'board'],
  '🛼': ['roller', 'skate', 'wheels'],
  '🚁': ['helicopter', 'chopper', 'aircraft'],
  '🛸': ['ufo', 'alien', 'spaceship'],
  '🚀': ['rocket', 'space', 'launch'],
  '🛰️': ['satellite', 'space', 'communication'],
  '🚂': ['train', 'locomotive', 'steam'],
  '🚃': ['train', 'car', 'railway'],
  '🚄': ['train', 'high', 'speed'],
  '🚅': ['train', 'bullet', 'fast'],
  '🚆': ['train', 'railway'],
  '🚇': ['metro', 'subway', 'underground'],
  '🚈': ['light', 'rail', 'train'],
  '🚉': ['station', 'train', 'railway'],
  '🚊': ['tram', 'trolley', 'streetcar'],
  '🚝': ['monorail', 'train'],
  '🚞': ['mountain', 'railway', 'train'],
  '🚋': ['tram', 'car', 'streetcar'],
  '⛵': ['sailboat', 'boat', 'sailing'],
  '🛶': ['canoe', 'boat', 'paddle'],
  '🚤': ['speedboat', 'boat', 'fast'],
  '🛥️': ['motor', 'boat', 'yacht'],
  '🛳️': ['passenger', 'ship', 'cruise'],
  '⛴️': ['ferry', 'boat', 'ship'],
  '🚢': ['ship', 'boat', 'cruise'],
  '⚓': ['anchor', 'ship', 'boat'],
  '🏠': ['house', 'home', 'building'],
  '🏡': ['house', 'home', 'garden'],
  '🏢': ['office', 'building', 'work'],
  '🏣': ['post', 'office', 'building'],
  '🏤': ['post', 'office', 'european'],
  '🏥': ['hospital', 'medical', 'building'],
  '🏦': ['bank', 'building', 'money'],
  '🏨': ['hotel', 'building', 'accommodation'],
  '🏩': ['love', 'hotel', 'building'],
  '🏪': ['convenience', 'store', 'shop'],
  '🏫': ['school', 'building', 'education'],
  '🏬': ['department', 'store', 'shopping'],
  '🏭': ['factory', 'building', 'industrial'],
  '🏯': ['castle', 'japanese', 'building'],
  '🏰': ['castle', 'european', 'building'],
  '🗼': ['tower', 'tokyo', 'landmark'],
  '🗽': ['statue', 'liberty', 'new', 'york'],
  '⛪': ['church', 'building', 'religion'],
  '🕌': ['mosque', 'building', 'religion'],
  '🛕': ['hindu', 'temple', 'building'],
  '🕍': ['synagogue', 'building', 'religion'],
  '⛩️': ['shinto', 'shrine', 'building'],
  '🕋': ['kaaba', 'mecca', 'building'],

  // Objects
  '📱': ['phone', 'mobile', 'cell', 'smartphone'],
  '💻': ['laptop', 'computer', 'pc'],
  '🖥️': ['desktop', 'computer', 'monitor'],
  '⌨️': ['keyboard', 'computer', 'type'],
  '🖱️': ['mouse', 'computer', 'click'],
  '🖨️': ['printer', 'computer', 'print'],
  '📷': ['camera', 'photo', 'picture'],
  '📸': ['camera', 'flash', 'photo'],
  '📹': ['video', 'camera', 'record'],
  '🎥': ['movie', 'camera', 'film'],
  '📺': ['tv', 'television', 'watch'],
  '📻': ['radio', 'music', 'listen'],
  '🎙️': ['microphone', 'studio', 'podcast'],
  '🎚️': ['level', 'slider', 'audio'],
  '🎛️': ['control', 'knobs', 'audio'],
  '⏰': ['alarm', 'clock', 'time'],
  '⏱️': ['stopwatch', 'timer', 'time'],
  '⏲️': ['timer', 'clock', 'time'],
  '🕰️': ['mantle', 'clock', 'time'],
  '⌛': ['hourglass', 'time', 'sand'],
  '⏳': ['hourglass', 'flowing', 'sand', 'time'],
  '📡': ['satellite', 'antenna', 'communication'],
  '🔋': ['battery', 'power', 'energy'],
  '🔌': ['plug', 'electric', 'power'],
  '💡': ['bulb', 'light', 'idea'],
  '🔦': ['flashlight', 'torch', 'light'],
  '🕯️': ['candle', 'light', 'flame'],
  '🧯': ['fire', 'extinguisher', 'safety'],
  '💰': ['money', 'bag', 'dollar'],
  '💵': ['dollar', 'bill', 'money'],
  '💴': ['yen', 'bill', 'money'],
  '💶': ['euro', 'bill', 'money'],
  '💷': ['pound', 'bill', 'money'],
  '💳': ['credit', 'card', 'payment'],
  '💎': ['diamond', 'gem', 'precious'],
  '🔧': ['wrench', 'tool', 'fix'],
  '🔨': ['hammer', 'tool', 'build'],
  '⚒️': ['hammer', 'pick', 'tool'],
  '🛠️': ['hammer', 'wrench', 'tool'],
  '⛏️': ['pick', 'tool', 'mine'],
  '🔩': ['nut', 'bolt', 'screw'],
  '⚙️': ['gear', 'settings', 'cog'],
  '🧲': ['magnet', 'attraction'],
  '🔫': ['gun', 'pistol', 'weapon'],
  '💣': ['bomb', 'explosive', 'danger'],
  '🧨': ['firecracker', 'explosive', 'dynamite'],
  '🔪': ['knife', 'blade', 'cut'],
  '🗡️': ['sword', 'blade', 'weapon'],
  '⚔️': ['crossed', 'swords', 'battle'],
  '🛡️': ['shield', 'protection', 'defense'],
  '🔮': ['crystal', 'ball', 'fortune'],
  '💈': ['barber', 'pole', 'haircut'],
  '⚗️': ['alembic', 'chemistry', 'lab'],
  '🔭': ['telescope', 'space', 'stars'],
  '🔬': ['microscope', 'science', 'lab'],
  '💊': ['pill', 'medicine', 'drug'],
  '💉': ['syringe', 'needle', 'vaccine'],
  '🌡️': ['thermometer', 'temperature', 'fever'],
  '🧹': ['broom', 'clean', 'sweep'],
  '🧽': ['sponge', 'clean', 'wash'],
  '🧴': ['lotion', 'bottle', 'soap'],
  '🔑': ['key', 'lock', 'access'],
  '🗝️': ['old', 'key', 'vintage'],
  '🚪': ['door', 'entrance', 'exit'],
  '🛋️': ['couch', 'sofa', 'furniture'],
  '🛏️': ['bed', 'sleep', 'furniture'],
  '🧸': ['teddy', 'bear', 'toy'],
  '🎁': ['gift', 'present', 'box'],
  '🎈': ['balloon', 'party', 'celebration'],
  '🎀': ['ribbon', 'bow', 'gift'],
  '🎊': ['confetti', 'ball', 'party'],
  '🎉': ['party', 'popper', 'celebration', 'tada'],
  '✉️': ['envelope', 'mail', 'letter'],
  '📩': ['envelope', 'arrow', 'mail'],
  '📨': ['incoming', 'envelope', 'mail'],
  '📧': ['email', 'mail', 'electronic'],
  '💌': ['love', 'letter', 'mail'],
  '📦': ['package', 'box', 'delivery'],
  '📋': ['clipboard', 'list', 'notes'],
  '📁': ['folder', 'file', 'directory'],
  '📂': ['open', 'folder', 'file'],
  '📄': ['page', 'document', 'file'],
  '📃': ['page', 'curl', 'document'],
  '📑': ['bookmark', 'tabs', 'document'],
  '📊': ['chart', 'bar', 'graph'],
  '📈': ['chart', 'increasing', 'graph'],
  '📉': ['chart', 'decreasing', 'graph'],
  '📓': ['notebook', 'book', 'notes'],
  '📔': ['notebook', 'decorative', 'cover'],
  '📒': ['ledger', 'notebook', 'book'],
  '📕': ['closed', 'book', 'red'],
  '📗': ['green', 'book', 'closed'],
  '📘': ['blue', 'book', 'closed'],
  '📙': ['orange', 'book', 'closed'],
  '📚': ['books', 'stack', 'library'],
  '📖': ['open', 'book', 'read'],
  '🔖': ['bookmark', 'mark', 'tag'],
  '📎': ['paperclip', 'attachment'],
  '🖇️': ['linked', 'paperclips'],
  '📐': ['triangular', 'ruler', 'math'],
  '📏': ['straight', 'ruler', 'measure'],
  '📌': ['pushpin', 'pin', 'location'],
  '📍': ['round', 'pushpin', 'location'],
  '✂️': ['scissors', 'cut', 'tool'],
  '🖊️': ['pen', 'write', 'ink'],
  '🖋️': ['fountain', 'pen', 'write'],
  '✒️': ['black', 'nib', 'pen'],
  '🖌️': ['paintbrush', 'art', 'paint'],
  '🖍️': ['crayon', 'color', 'art'],
  '📝': ['memo', 'note', 'write'],
  '✏️': ['pencil', 'write', 'draw'],
  '🔍': ['magnifying', 'glass', 'search'],
  '🔎': ['magnifying', 'glass', 'right', 'search'],

  // Symbols
  '💯': ['hundred', 'points', 'perfect', 'score'],
  '💢': ['anger', 'symbol', 'mad'],
  '💥': ['collision', 'explosion', 'boom'],
  '💫': ['dizzy', 'star', 'sparkle'],
  '💬': ['speech', 'balloon', 'talk'],
  '💭': ['thought', 'balloon', 'think'],
  '🗯️': ['right', 'anger', 'bubble'],
  '♠️': ['spade', 'suit', 'cards'],
  '♥️': ['heart', 'suit', 'cards'],
  '♦️': ['diamond', 'suit', 'cards'],
  '♣️': ['club', 'suit', 'cards'],
  '🃏': ['joker', 'card', 'game'],
  '🎴': ['flower', 'playing', 'cards'],
  '🀄': ['mahjong', 'red', 'dragon'],
  '🔇': ['muted', 'speaker', 'quiet'],
  '🔈': ['speaker', 'low', 'volume'],
  '🔉': ['speaker', 'medium', 'volume'],
  '🔊': ['speaker', 'high', 'volume'],
  '📢': ['loudspeaker', 'announcement'],
  '📣': ['megaphone', 'cheering'],
  '📯': ['postal', 'horn', 'trumpet'],
  '🔔': ['bell', 'notification', 'ring'],
  '🔕': ['bell', 'slash', 'mute'],
  '🎵': ['musical', 'note', 'music'],
  '🎶': ['musical', 'notes', 'music'],
  '💲': ['heavy', 'dollar', 'sign'],
  '💱': ['currency', 'exchange'],
  '™️': ['trade', 'mark', 'trademark'],
  '©️': ['copyright', 'symbol'],
  '®️': ['registered', 'symbol'],
  '〰️': ['wavy', 'dash', 'line'],
  '➰': ['curly', 'loop'],
  '➿': ['double', 'curly', 'loop'],
  '🔚': ['end', 'arrow', 'finish'],
  '🔙': ['back', 'arrow', 'return'],
  '🔛': ['on', 'arrow', 'mark'],
  '🔝': ['top', 'arrow', 'up'],
  '🔜': ['soon', 'arrow', 'coming'],
  '✔️': ['check', 'mark', 'yes'],
  '☑️': ['check', 'box', 'mark'],
  '🔘': ['radio', 'button', 'select'],
  '⚪': ['white', 'circle', 'medium'],
  '⚫': ['black', 'circle', 'medium'],
  '🔴': ['red', 'circle', 'large'],
  '🔵': ['blue', 'circle', 'large'],
  '🟢': ['green', 'circle', 'large'],
  '🟡': ['yellow', 'circle', 'large'],
  '🟠': ['orange', 'circle', 'large'],
  '🟣': ['purple', 'circle', 'large'],
  '🟤': ['brown', 'circle', 'large'],
  '⬛': ['black', 'large', 'square'],
  '⬜': ['white', 'large', 'square'],
  '◼️': ['black', 'medium', 'square'],
  '◻️': ['white', 'medium', 'square'],
  '◾': ['black', 'medium', 'small', 'square'],
  '◽': ['white', 'medium', 'small', 'square'],
  '▪️': ['black', 'small', 'square'],
  '▫️': ['white', 'small', 'square'],
  '🟥': ['red', 'square', 'large'],
  '🟧': ['orange', 'square', 'large'],
  '🟨': ['yellow', 'square', 'large'],
  '🟩': ['green', 'square', 'large'],
  '🟦': ['blue', 'square', 'large'],
  '🟪': ['purple', 'square', 'large'],
  '🟫': ['brown', 'square', 'large'],
  '🔶': ['orange', 'diamond', 'large'],
  '🔷': ['blue', 'diamond', 'large'],
  '🔸': ['orange', 'diamond', 'small'],
  '🔹': ['blue', 'diamond', 'small'],
  '🔺': ['red', 'triangle', 'up'],
  '🔻': ['red', 'triangle', 'down'],
  '💠': ['diamond', 'shape', 'flower'],
  '🔳': ['white', 'square', 'button'],
  '🔲': ['black', 'square', 'button'],

  // Common words and expressions
  '🤷': ['shrug', 'dunno', 'whatever', 'idk'],
  '🤦': ['facepalm', 'doh', 'stupid', 'mistake'],
  '🙈': ['see', 'no', 'evil', 'monkey'],
  '🙉': ['hear', 'no', 'evil', 'monkey'],
  '🙊': ['speak', 'no', 'evil', 'monkey'],
  '💸': ['money', 'with', 'wings', 'expensive'],
  '🎯': ['direct', 'hit', 'target', 'bullseye'],
  '🚀': ['rocket', 'launch', 'fast', 'growth'],
  '⚡': ['zap', 'lightning', 'fast', 'energy'],
  '🔥': ['fire', 'hot', 'trending', 'awesome'],
  '💎': ['diamond', 'precious', 'valuable'],
  '🏆': ['trophy', 'win', 'champion', 'best'],
  '🎉': ['celebration', 'party', 'congrats', 'yay'],
  '👑': ['crown', 'king', 'queen', 'royal'],
  '💪': ['strong', 'power', 'muscle', 'strength'],
  '🧠': ['brain', 'smart', 'think', 'intelligence'],
  '👀': ['eyes', 'looking', 'watching', 'see'],
  '👂': ['ear', 'listening', 'hear'],
  '👃': ['nose', 'smell'],
  '👄': ['mouth', 'lips', 'kiss'],
  '👅': ['tongue', 'taste', 'lick']
};

const STORAGE_KEY = 'chatter_emoji_usage';

export const useEmojis = () => {
  const [recentEmojis, setRecentEmojis] = useState([]);
  const [frequentEmojis, setFrequentEmojis] = useState({});

  // Load emoji usage data from localStorage
  useEffect(() => {
    try {
      const stored = localStorage.getItem(STORAGE_KEY);
      if (stored) {
        const data = JSON.parse(stored);
        setRecentEmojis(data.recent || []);
        setFrequentEmojis(data.frequent || {});
      }
    } catch (error) {
      console.warn('Failed to load emoji usage data:', error);
    }
  }, []);

  // Save emoji usage
  const saveEmojiUsage = (emoji) => {
    try {
      const newRecent = [emoji, ...recentEmojis.filter(e => e !== emoji)].slice(0, 32);
      const newFrequent = { ...frequentEmojis, [emoji]: (frequentEmojis[emoji] || 0) + 1 };
      
      setRecentEmojis(newRecent);
      setFrequentEmojis(newFrequent);
      
      localStorage.setItem(STORAGE_KEY, JSON.stringify({
        recent: newRecent,
        frequent: newFrequent
      }));
    } catch (error) {
      console.warn('Failed to save emoji usage:', error);
    }
  };

  // Enhanced emoji search
  const searchEmojis = useMemo(() => {
    return (query) => {
      if (!query.trim()) return [];
      
      const searchTerm = query.toLowerCase().trim();
      const results = [];
      
      // Search through emoji keywords
      Object.entries(EMOJI_KEYWORDS).forEach(([emoji, keywords]) => {
        const score = keywords.reduce((acc, keyword) => {
          if (keyword.includes(searchTerm)) {
            // Exact match gets higher score
            if (keyword === searchTerm) return acc + 10;
            // Starts with gets medium score
            if (keyword.startsWith(searchTerm)) return acc + 5;
            // Contains gets lower score
            return acc + 1;
          }
          return acc;
        }, 0);
        
        if (score > 0) {
          results.push({ emoji, score });
        }
      });
      
      // Sort by score (highest first) and return emojis
      return results
        .sort((a, b) => b.score - a.score)
        .map(result => result.emoji)
        .slice(0, 50); // Limit results
    };
  }, []);

  // Get frequently used emojis
  const getFrequentEmojis = useMemo(() => {
    return (limit = 16) => {
      return Object.entries(frequentEmojis)
        .sort(([,a], [,b]) => b - a)
        .slice(0, limit)
        .map(([emoji]) => emoji);
    };
  }, [frequentEmojis]);



  return {
    recentEmojis,
    frequentEmojis,
    saveEmojiUsage,
    searchEmojis,
    getFrequentEmojis
  };
}; 